GET http://localhost:3001/api/persons/

###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Otro nombre de prueba",
    "number": "1234567890"
}

###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "123456789"
}

###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Nombre de prueba"
}

###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "No",
    "number": "123456"
}

###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Nombre 1"
}
###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "123456"
}
###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Nombre de prueba",
    "number": "123"
}